### ISSUE TITLE
Website source?

### ISSUE THREAD

**Issue by NonsensicalOne** [indexxing/PolyPlus#12]
![Screenshot_20240801_232126](https://github.com/user-attachments/assets/6cce7c47-cbba-40dc-b455-31c05ee1cc74)
take this with a fine grain of salt, it looks horrible, and i wanna fix it (or not)

unrelated stuff cuz my discord went boom and cant tell those there:
1. https://devpixels.xyz is back

2. ![102127_7xisg4qixn7ry81_custom](https://github.com/user-attachments/assets/01581ce7-9cd9-446e-8e5f-762155a70099)

**Comment by indexxing** [comment]
I know the website is ugly, looking into remaking it. Nobody visits it anyway so what is the point?

1. I know DevPixels site is back, we were messaging back and forth the day he brought it back and he told me.

**Comment by NonsensicalOne** [comment]
> I know the website is ugly, looking into remaking it. Nobody visits it anyway so what is the point?

i visit it, jokes aside, if no one visits it, then whats the point of the website existing?

**Comment by NonsensicalOne** [comment]
anyway lemme close this

**Comment by indexxing** [comment]
> > I know the website is ugly, looking into remaking it. Nobody visits it anyway so what is the point?
> 
> 
> 
> i visit it, jokes aside, if no one visits it, then whats the point of the website existing?

I used to use the website to share info on the extension but most people either don't trust Vercel links or just didn't care enough with the old download method. I realized after the website was created (6 months ago)
