### ISSUE TITLE
Game Profile Request

### ISSUE THREAD

**Issue by ItsLuiggiYahoo** [indexxing/PolyPlus#5]
I would like to request a game profile for my game: [Isolation: Brix High School[CLOSED BETA TESTING]](https://polytoria.com/places/7930)

```
{"gameTitle":"Isolation: Brix High School","bg":"#0148af","accent":"#986c6a","secondary":"#b7d3f2","cardBg":"#313131","text":"#fff"}
```

**Comment by indexxing** [comment]
Closed for now, please make a new GitHub issue when game profiles are fully developed.
